### ISSUE TITLE
Errors when `npm run build`

### ISSUE THREAD

**Issue by mashuklya** [GoogleChromeLabs/ProgressiveWordPress#15]
```
maria@MacBook-Pro-Maria:~/Downloads/ProgressiveWordPress$  npm run build

> ProgressiveWordPress@0.0.3412 build /Users/maria/Downloads/ProgressiveWordPress
> npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js

npm WARN using --force I sure hope you know what you are doing.
v0.0.3413
/Users/maria/Downloads/ProgressiveWordPress/build.js:32
async function copyStatic() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ProgressiveWordPress@0.0.3412 build: `npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ProgressiveWordPress@0.0.3412 build script 'npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ProgressiveWordPress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ProgressiveWordPress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ProgressiveWordPress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maria/Downloads/ProgressiveWordPress/npm-debug.log
```

**Comment by surma** [comment]
Yeah, as it says in the README, you need Node 8 or newer. You have Node 6 which is very old at this point. I urge you to update :)
